services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'
      
  # mongodb:
  #   image: 'mongo:latest'
  #   environment:
  #     - 'MONGO_INITDB_DATABASE=mydatabase'
  #     - 'MONGO_INITDB_ROOT_USERNAME=myuser'
  #     - 'MONGO_INITDB_ROOT_PASSWORD=secret'
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - ./data/db:/data/db
  #   container_name: mongodb_container
  #   networks:
  #     - ollama-docker

  ollama:
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    volumes:
      - .:/code
      - ../models/ollama/ollama:/root/.ollama
    container_name: ollama_latest
    pull_policy: always
    tty: true
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
